permalink: /:title/
paginate: 10 # how many posts on a page
remote_theme: EthanMcBloxxer/jekyll-theme-writeas@main
plugins:
  - jekyll-remote-theme
  - jekyll-paginate

## MAIN ##  
title: "La voce dell'Alleanza" # title of blog or your name
subtitle: "Il podcast dell'Italian Translation Alliance" # subtitle of blog or your position / minbio
links:
  about: /about/
  contact: mailto:italian.translation.alliance@gmail.com
  rss: /feed.xml
credit: false # show a footer "published with jekyll-theme-writeas" (only on posts)

## FONTS ##
serif: true # use a serif font (Lora) instead of sans-serif (Open Sans); "monospace" is also supported

## PAGINATE ##
paginate_path: "/page/:num/" # page 2 would be served at /page/2/
older_text: false # text to be displayed for older posts nav
newer_text: false # text to be displayed for newer posts nav

## COLORS ##
background: "#f5f5f5" # page background color in HEX
text: "#111" # text color in HEX
accent: "#777" # text accent (subtitles, read more, etc) in HEX
link: "#9f9fff" # link color in HEX
code: "#586e75" # default code color in HEX
